Lecture 1 Exerciese: 1-10


In [1]:
#1, 2
my_age=24 #Store my age in the variable my_age
my_name="Tianheng Huang" #Store my name in the variable my_name
pet=1 #Store the number of pets I've ever owned in the variable pet

In [2]:
#3
print(my_age)
print(my_name)
print(pet)

24
Tianheng Huang
1


In [3]:
#4
print("I was born "+str(my_age)+" years ago.")
print(str(my_name)+" is my name.")
print("I have owned "+str(pet)+" pet in my life.")

I was born 24 years ago.
Tianheng Huang is my name.
I have owned 1 pet in my life.


In [4]:
#5
my_age=my_age+1
print("Congratulations, now you are "+str(my_age)+".")

Congratulations, now you are 25.


In [5]:
#6
if my_age>=21:
  print("You can drink! You have been able to drink for "+str(my_age-21)+" years.")
else:
  print("You can't drink. You need to wait "+str(21-my_age)+" years.")

You can drink! You have been able to drink for 4 years.


In [6]:
#7
for i in range(30):
  if i+1<21:
    print("A "+str(i+1)+" year old cannot drink and must wait "+str(21-(i+1))+" more years.")
  else:
    print("A "+str(i+1)+" year old has been able to drink for "+str((i+1)-21)+" years.")

A 1 year old cannot drink and must wait 20 more years.
A 2 year old cannot drink and must wait 19 more years.
A 3 year old cannot drink and must wait 18 more years.
A 4 year old cannot drink and must wait 17 more years.
A 5 year old cannot drink and must wait 16 more years.
A 6 year old cannot drink and must wait 15 more years.
A 7 year old cannot drink and must wait 14 more years.
A 8 year old cannot drink and must wait 13 more years.
A 9 year old cannot drink and must wait 12 more years.
A 10 year old cannot drink and must wait 11 more years.
A 11 year old cannot drink and must wait 10 more years.
A 12 year old cannot drink and must wait 9 more years.
A 13 year old cannot drink and must wait 8 more years.
A 14 year old cannot drink and must wait 7 more years.
A 15 year old cannot drink and must wait 6 more years.
A 16 year old cannot drink and must wait 5 more years.
A 17 year old cannot drink and must wait 4 more years.
A 18 year old cannot drink and must wait 3 more years.
A 19 yea

In [7]:
#8
for i in range(30):
  if i+1<21:
    print("A "+str(i+1)+" year old cannot drink and must wait "+str(21-(i+1))+" more years.")
  else:
    print("A "+str(i+1)+" year old has been able to drink for "+str((i+1)-21)+" years.")
  if i+1==10:
    break

A 1 year old cannot drink and must wait 20 more years.
A 2 year old cannot drink and must wait 19 more years.
A 3 year old cannot drink and must wait 18 more years.
A 4 year old cannot drink and must wait 17 more years.
A 5 year old cannot drink and must wait 16 more years.
A 6 year old cannot drink and must wait 15 more years.
A 7 year old cannot drink and must wait 14 more years.
A 8 year old cannot drink and must wait 13 more years.
A 9 year old cannot drink and must wait 12 more years.
A 10 year old cannot drink and must wait 11 more years.


In [8]:
#9
i=0
while (i<30):
  i=i+1
  if i<21:
    print("A "+str(i)+" year old cannot drink and must wait "+str(21-i)+" more years.")
  else:
    print("A "+str(i)+" year old has been able to drink for "+str(i-21)+" years.")

A 1 year old cannot drink and must wait 20 more years.
A 2 year old cannot drink and must wait 19 more years.
A 3 year old cannot drink and must wait 18 more years.
A 4 year old cannot drink and must wait 17 more years.
A 5 year old cannot drink and must wait 16 more years.
A 6 year old cannot drink and must wait 15 more years.
A 7 year old cannot drink and must wait 14 more years.
A 8 year old cannot drink and must wait 13 more years.
A 9 year old cannot drink and must wait 12 more years.
A 10 year old cannot drink and must wait 11 more years.
A 11 year old cannot drink and must wait 10 more years.
A 12 year old cannot drink and must wait 9 more years.
A 13 year old cannot drink and must wait 8 more years.
A 14 year old cannot drink and must wait 7 more years.
A 15 year old cannot drink and must wait 6 more years.
A 16 year old cannot drink and must wait 5 more years.
A 17 year old cannot drink and must wait 4 more years.
A 18 year old cannot drink and must wait 3 more years.
A 19 yea

In [9]:
#10
my_age=int(input("How old are you? > "))
if my_age>=21:
  print("You can drink! You have been able to drink for "+str(my_age-21)+" years.")
else:
  print("You can't drink. You need to wait "+str(21-my_age)+" years.")

How old are you? > 0
You can't drink. You need to wait 21 years.


Lecture 2 Exercises: 1-15

In [10]:
#1
import numpy as np
ages=np.array([52,57])
names=np.array(["Ruby","Hill"])
numbers=np.array(range(100))+1


In [11]:
#2
print(ages)
print(names)
print(numbers)



[52 57]
['Ruby' 'Hill']
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [12]:
#3
print(ages[0])
print(names[0])



52
Ruby


In [13]:
#4
length=len(names)
print(length)

2


In [14]:
#5
print(names[length-1])



Hill


In [15]:
#6
print(np.delete(names,0))


['Hill']


In [16]:
#6a
names=np.array(["Ruby","Hill","Jack","Kevin"])
ages=np.array([52,57,24,24])
print(names[1:4])



['Hill' 'Jack' 'Kevin']


In [17]:
#6b
names[np.array([0,1,3])]="Bob"
print(names)


['Bob' 'Bob' 'Jack' 'Bob']


In [18]:
#7
print(np.delete(names,1))



['Bob' 'Jack' 'Bob']


In [19]:
#8
names=np.append(names,"Baby")
ages=np.append(ages,0)
print(names)
print(ages)



['Bob' 'Bob' 'Jack' 'Bob' 'Baby']
[52 57 24 24  0]


In [20]:
#9
from statistics import median

print(sum(ages)/len(ages))
print(median(ages))


31.4
24


In [21]:
#10
double_family=np.concatenate([names,names])
print(double_family)



['Bob' 'Bob' 'Jack' 'Bob' 'Baby' 'Bob' 'Bob' 'Jack' 'Bob' 'Baby']


In [22]:
#11
print(ages==0) #The 5th member is aged 0



[False False False False  True]


In [23]:
#12
any(ages==0) #Yes, there is at least one member aged 0



True

In [24]:
#13
sum(ages==0) #There is one member aged 0



1

In [25]:
#14
n=len(ages)
new_ages=(np.array(range(n))+1)*10
print(new_ages)

[10 20 30 40 50]


In [26]:
#15
ages==new_ages

array([False, False, False, False, False])